var masterData = [
                { h: "你", p: "nǐ", v: "bạn", r: "Bộ Nhân (亻) - người + bộ Mịch (冖) + bộ Tiểu (小)." },
                { h: "你们", p: "nǐmen", v: "các bạn", r: "Chữ 们 có bộ Nhân (亻) chỉ người." },
                { h: "我", p: "wǒ", v: "tôi", r: "Bộ Qua (戈) - binh khí. Ý nghĩa: Cái tôi mạnh mẽ." },
                { h: "我们", p: "wǒmen", v: "chúng tôi", r: "我 (Tôi) + 们 (số nhiều)." },
                { h: "也", p: "yě", v: "cũng", r: "Nguyên thủy là hình con rắn." },
                { h: "他", p: "tā", v: "anh ấy", r: "Bộ Nhân (亻) - chỉ nam giới." },
                { h: "她", p: "tā", v: "cô ấy", r: "Bộ Nữ (女) - chỉ nữ giới." },
                { h: "它", p: "tā", v: "nó", r: "Bộ Miên (宀) - mái nhà. Dùng cho vật." },
                { h: "他们", p: "tāmen", v: "họ (nam)", r: "Sử dụng 'tha' nam làm đại diện chung." },
                { h: "她们", p: "tāmen", v: "họ (nữ)", r: "Sử dụng 'tha' nữ làm đại diện chung." },
                { h: "大家", p: "dàjiā", v: "mọi người", r: "Đại (大) - lớn + Gia (家) - nhà (bộ Miên 宀)." },
                { h: "朋友", p: "péngyou", v: "bạn bè", r: "Bằng (朋) - 2 vầng trăng + Hữu (友) - bộ Hựu." },
                { h: "爷爷", p: "yéye", v: "ông nội", r: "Bộ Phụ (父) - cha/ông." },
                { h: "奶奶", p: "nǎinai", v: "bà nội", r: "Bộ Nữ (女) - phụ nữ/bà." },
                { h: "外公", p: "wàigōng", v: "ông ngoại", r: "Ngoại (外) - bộ Tịch + Công (公) - bộ Bát." },
                { h: "外婆", p: "wàipó", v: "bà ngoại", r: "Ngoại (外) + Bà (婆) - có bộ Nữ (女)." },
                { h: "爸爸", p: "bàba", v: "bố", r: "Bộ Phụ (父) - cha, người đàn ông trụ cột." },
                { h: "妈妈", p: "māma", v: "mẹ", r: "Bộ Nữ (女) - phụ nữ + chữ Mã (马) tượng thanh." },
                { h: "父母", p: "fùmǔ", v: "cha mẹ", r: "Phụ (父) + Mẫu (母)." },
                { h: "孩子", p: "háizi", v: "con cái", r: "Bộ Tử (子) - đứa trẻ." },
                { h: "儿女", p: "érnǚ", v: "con cái", r: "Bộ nhi (儿) - bộ nữ(女)." },
                { h: "女儿", p: "nǚ'ér", v: "con gái", r: "Bộ Nữ (女) + bộ Nhi (儿)." },
                { h: "儿子", p: "érzi", v: "con trai", r: "Bộ Nhi (儿) + bộ Tử (子)." },
                { h: "哥哥", p: "gēge", v: "anh trai", r: "Gồm 2 bộ Khả (可) chồng lên nhau." },
                { h: "姐姐", p: "jiějie", v: "chị gái", r: "Bộ Nữ (女) + bộ Thả (且)." },
                { h: "妹妹", p: "mèimei", v: "em gái", r: "Bộ Nữ (女) + chữ Vị (未) - chưa trưởng thành." },
                { h: "弟弟", p: "dìdi", v: "em trai", r: "Bộ Cung (弓) + nét phẩy." },
                { h: "老师", p: "lǎoshī", v: "thầy cô", r: "Bộ Lão (耂) - già + bộ Cân (巾) - khăn." },
                { h: "学生", p: "xuésheng", v: "học sinh", r: "Bộ Tử (子) - con trẻ + bộ Sinh (生)." },
                { h: "同学", p: "tóngxué", v: "bạn học", r: "Đồng (同) - bộ Quynh + Học (学)." },
                { h: "工人", p: "gōngrén", v: "công nhân", r: "Công (工) - thợ + Nhân (人) - người." },
                { h: "老板", p: "lǎobǎn", v: "ông chủ", r: "Lão (老) + Bản (板) - có bộ Mộc (木)." },
                { h: "医生", p: "yīshēng", v: "bác sĩ", r: "Y (医) - bộ Phương 匚 + Sinh (生)." },
                { h: "爱人", p: "àirén", v: "người yêu, vợ", r: "Ái (爱) - yêu + Nhân (人) - người." },
                { h: "女友", p: "nǚyǒu", v: "bạn gái", r: "Nữ (女) + Hữu (友)." },
                { h: "男友", p: "nányǒu", v: "bạn trai", r: "Nam (男) + Hữu (友)." },
                { h: "年", p: "nián", v: "năm", r: "Can (干)." },
                { h: "今年", p: "jīnnián", v: "năm nay", r: "Kim (今) + Niên (年)." },
                { h: "去年", p: "qùnián", v: "năm ngoái", r: "Khứ (去) + Niên (年)." },
                { h: "每年", p: "měinián", v: "hàng năm", r: "Mỗi (每) + Niên (年)." },
                { h: "月", p: "yuè", v: "tháng", r: "Bộ Nguyệt (月)." },
                { h: "这个月", p: "zhège yuè", v: "tháng này", r: "Giá (这) - bộ Quai xước." },
                { h: "上个月", p: "shàng ge yuè", v: "tháng trước", r: "Thượng (上)." },
                { h: "下个月", p: "xià ge yuè", v: "tháng sau", r: "Hạ (下)." },
                { h: "每个月", p: "měige yuè", v: "hàng tháng", r: "Mỗi (每) - bộ Vô + Nguyệt (月)." },
                { h: "号", p: "hào", v: "số ngày", r: "Bộ Khẩu (口)." },
                { h: "日", p: "rì", v: "ngày", r: "Hình mặt trời." },
                { h: "天", p: "tiān", v: "ngày, trời", r: "Bộ Đại (大)." },
                { h: "今天", p: "jīntiān", v: "hôm nay", r: "Kim (今) + Thiên (天)." },
                { h: "明天", p: "míngtiān", v: "ngày mai", r: "Minh (明) + Thiên (天)." },
                { h: "昨天", p: "zuótiān", v: "hôm qua", r: "Tạc (昨) - bộ Nhật." },
                { h: "后天", p: "hòutiān", v: "ngày kia", r: "Hậu (post) - sau." },
                { h: "每天", p: "měitiān", v: "hàng ngày", r: "Mỗi (每) + Thiên (天)." },
                { h: "星期", p: "xīngqī", v: "thứ tuần", r: "Tinh (星) + Kỳ (期)." },
                { h: "周", p: "zhōu", v: "thứ tuần", r: "Bộ Quynh (冂)." },
                { h: "礼拜", p: "lǐbài", v: "thứ tuần", r: "Lễ (礼) + Bái (拜)." },
                { h: "周末", p: "zhōumò", v: "cuối tuần", r: "Chu (周) + Mạt (末) - ngọn/hết." },
                { h: "上午", p: "shàngwǔ", v: "buổi sáng", r: "Ngọ (午)." },
                { h: "早上", p: "zǎoshang", v: "buổi sáng", r: "Tảo (早) + Thượng (上)." },
                { h: "中午", p: "zhōngwǔ", v: "buổi trưa", r: "Trung (中) + Ngọ (午)." },
                { h: "下午", p: "xiàwǔ", v: "buổi chiều", r: "Hạ (下) + Ngọ (午)." },
                { h: "晚上", p: "wǎnshang", v: "buổi tối", r: "Vãn (晚) + Thượng (上)." },
                { h: "点", p: "diǎn", v: "giờ", r: "Bộ Hỏa (灬)." },
                { h: "分", p: "fēn", v: "phút", r: "Bộ Bát (八) + Đao (刀)." },
                { h: "分钟", p: "fēnzhōng", v: "phút", r: "Phân (分) + Chung (钟)." },
                { h: "秒", p: "miǎo", v: "giây", r: "Bộ Hòa (禾) + Thiểu (少)." },
                { h: "星期日", p: "xīngqīrì", v: "chủ nhật", r: "Tinh Kỳ + Nhật (日)." },
                { h: "星期天", p: "xīngqītiān", v: "chủ nhật", r: "Tinh Kỳ + Thiên (天)." },
                { h: "手机", p: "shǒujī", v: "điện thoại di động", r: "Thủ (手) - tay + Cơ (机)." },
                { h: "电话", p: "diànhuà", v: "điện thoại", r: "Điện (电) + Thoại (话) - bộ Ngôn." },
                { h: "谁", p: "shéi", v: "ai", r: "Bộ Ngôn (讠) - lời nói + bộ Truy (隹)." },
                { h: "什么", p: "shénme", v: "cái gì", r: "Thập (什) - bộ Nhân + Ma (么) - bộ Phiệt." },
                { h: "哪", p: "nǎ", v: "nào", r: "Bộ Ấp (阝) nằm bên phải." },
                { h: "哪儿", p: "nǎr", v: "đâu", r: "哪 + bộ Nhi (儿) dùng làm âm cuốn lưỡi." },
                { h: "为什么", p: "wèishénme", v: "vì sao", r: "Vi (为) + Thập Ma (import)." },
                { h: "家", p: "jiā", v: "nhà", r: "Bộ Miên (宀) - mái nhà." },
                { h: "怎么", p: "zěnme", v: "làm sao, thế nào", r: "Chẩm (怎) có bộ Tâm (心) ở dưới." },
                { h: "多少", p: "duōshǎo", v: "bao nhiêu", r: "Đa (多) - 2 bộ Tịch (đêm) + Thiểu (少)." },
                { h: "几", p: "jǐ", v: "mấy", r: "Bộ Kỷ (几) - cái bàn nhỏ." },
                { h: "怎么样", p: "zěnmeyàng", v: "như thế nào", r: "Chữ Mẫu (样) có bộ Mộc (木)." },
                { h: "医院", p: "yīyuàn", v: "bệnh viện", r: "Bộ Phương (匚) + Bộ Phụ (阝)." },
                { h: "公司", p: "gōngsī", v: "công ty", r: "Công (公) + Ti (司)." },
                { h: "学校", p: "xuéxiào", v: "trường học", r: "Bộ Tử (子) + Bộ Mộc (木)." },
                { h: "公园", p: "gōngyuán", v: "công viên", r: "Công (公) + Viên (园) - bộ Vi (囗)." },
                { h: "商店", p: "shāngdiàn", v: "cửa hàng", r: "Bộ Khẩu (口) + Bộ Quảng (广)." },
                { h: "花店", p: "huàdiàn", v: "cửa hàng hoa", r: "Bộ Thảo (艹) - cây cỏ." },
                { h: "鞋店", p: "xiédiàn", v: "cửa hàng giày dép", r: "Bộ Cách (革) - da thuộc + Bộ Quảng (广)." },
                { h: "电影院", p: "diànyǐngyuàn", v: "rạp chiếu phim", r: "Điện ảnh + Viện (院)." },
                { h: "市场", p: "shìchǎng", v: "chợ", r: "Bộ Khẩu (口) + Bộ Thổ (土)." },
                { h: "超市", p: "chāoshì", v: "siêu thị", r: "Bộ Tẩu (走) + Bộ Khẩu (口)." },
                { h: "水果店", p: "shuǐguǒdiàn", v: "cửa hàng hoa quả", r: "Thủy (水) + Quả (果) + Điếm (店)." },
                { h: "越南", p: "Yuènán", v: "VN", r: "Việt (越) + Nam (南)." },
                { h: "中国", p: "Zhōngguó", v: "TQ", r: "Trung (中) + Quốc (国)." },
                { h: "日本", p: "Rìběn", v: "Nhật Bản", r: "Nhật (日) + Bản (本)." },
                { h: "韩国", p: "Hánguó", v: "Hàn Quốc", r: "Hàn (韩) + Quốc (国)." },
                { h: "美国", p: "Měiguó", v: "Mỹ", r: "Mỹ (美) + Quốc (国)." },
                { h: "英国", p: "Yīngguó", v: "Anh", r: "Anh (英) + Quốc (国)." },
                { h: "俄国", p: "Éguó", v: "Nga", r: "" },
                { h: "德国", p: "Déguó", v: "Đức", r: "Đức (德) + Quốc (国)." },
                { h: "法国", p: "Fǎguó", v: "Pháp", r: "Pháp (法) + Quốc (国)." },
                { h: "古巴", p: "Gǔbā", v: "Cuba", r: "" },
                { h: "老挝", p: "Lǎowō", v: "Lào", r: "" },
                { h: "伊拉克", p: "Yīlākè", v: "Iraq", r: "" },
                { h: "意大利", p: "Yìdàlì", v: "Ý", r: "" },
                { h: "葡萄牙", p: "Pútáoyá", v: "Bồ Đào Nha", r: "" },
                { h: "西班牙", p: "Xībānyá", v: "Tây Ban Nha", r: "" },
                { h: "加拿大", p: "Jiānádà", v: "Canada", r: "" },
                { h: "外语", p: "wàiyǔ", v: "Ngoại ngữ", r: "" },
                { h: "越南语", p: "Yuènányǔ", v: "Tiếng Việt", r: "" },
                { h: "汉语", p: "Hànyǔ", v: "Tiếng Trung Quốc", r: "" },
                { h: "中文", p: "Zhōngwén", v: "Tiếng Trung Quốc", r: "" },
                { h: "英语", p: "Yīngyǔ", v: "Tiếng Anh", r: "" },
                { h: "英文", p: "Yīngwén", v: "Tiếng Anh", r: "" },
                { h: "韩语", p: "Hányǔ", v: "Tiếng Hàn Quốc", r: "" },
                { h: "日语", p: "Rìyǔ", v: "Tiếng Nhật", r: "" },
                { h: "俄语", p: "Éyǔ", v: "Tiếng Nga", r: "" },
                { h: "德语", p: "Déguó", v: "Tiếng Đức", r: "" },
                { h: "马来语", p: "Mǎláiyǔ", v: "Tiếng Malaysia", r: "" },
                { h: "葡萄牙语", p: "Pútáoyáyǔ", v: "Tiếng Bồ Đào Nha", r: "" },
                { h: "西班牙语", p: "Xībānyáyǔ", v: "Tiếng Tây Ban Nha", r: "" },
                { h: "法语", p: "Fǎyǔ", v: "Tiếng Pháp", r: "" },
                { h: "河内", p: "Hénèi", v: "Hà Nội", r: "" },
                { h: "海防", p: "Hǎifáng", v: "Hải Phòng", r: "" },
                { h: "胡志明市", p: "Húzhìmíng Shì", v: "Thành phố Hồ Chí Minh", r: "" },
                { h: "北宁", p: "Běiníng", v: "Bắc Ninh", r: "" },
                { h: "北京", p: "Běijīng", v: "Bắc Kinh", r: "" },
                { h: "上海", p: "Shànghǎi", v: "Thượng Hải", r: "" },
                { h: "天津", p: "Tiānjīn", v: "Thiên Tân", r: "" },
                { h: "重庆", p: "Chóngqìng", v: "Trùng Khánh", r: "" },
                { h: "广东", p: "Guǎngdōng", v: "Quảng Đông", r: "" },
                { h: "狗", p: "gǒu", v: "Chó", r: "" },
                { h: "猫", p: "māo", v: "Mèo", r: "" },
                { h: "鸡", p: "jī", v: "Gà", r: "" },
                { h: "鱼", p: "yú", v: "Cá", r: "" },
                { h: "鸟", p: "niǎo", v: "Chim", r: "" },
                { h: "羊", p: "yáng", v: "Dê", r: "" },
                { h: "蛇", p: "shé", v: "Rắn", r: "" },
                { h: "老鼠", p: "lǎoshǔ", v: "Chuột", r: "" },
                { h: "老虎", p: "lǎohǔ", v: "Hổ", r: "" },
                { h: "龙", p: "lóng", v: "Rồng", r: "" },
                { h: "猴子", p: "hóuzi", v: "Khỉ", r: "" },
                { h: "茶", p: "chá", v: "Trà", r: "" },
                { h: "菜", p: "cài", v: "Món ăn", r: "" },
                { h: "衣服", p: "yīfu", v: "Quần áo", r: "" },
                { h: "水果", p: "shuǐguǒ", v: "Hoa quả", r: "" },
                { h: "苹果", p: "píngguǒ", v: "Táo", r: "" },
                { h: "书", p: "shū", v: "Sách", r: "" },
                { h: "笔", p: "bǐ", v: "Bút", r: "" },
                { h: "杯子", p: "bēizi", v: "Cốc", r: "" },
                { h: "桌子", p: "zhuōzi", v: "Bàn", r: "" },
                { h: "椅子", p: "yǐzi", v: "Ghế", r: "" },
                { h: "电视", p: "diànshì", v: "TV", r: "" },
                { h: "电脑", p: "diànnǎo", v: "Máy tính", r: "" },
                { h: "汽车", p: "qìchē", v: "Ô tô", r: "" },
                { h: "公共汽车", p: "gōnggòng qìchē", v: "Xe buýt", r: "" },
                { h: "出租车", p: "chūzūchē", v: "Taxi", r: "" },
                { h: "摩托车", p: "mótuōchē", v: "Xe máy", r: "" },
                { h: "自行车", p: "zìxíngchē", v: "Xe đạp", r: "" },
                { h: "白色", p: "báisè", v: "Màu trắng", r: "" },
                { h: "黑色", p: "hēisè", v: "Màu đen", r: "" },
                { h: "西瓜", p: "xīguā", v: "Dưa hấu", r: "" },
                { h: "说", p: "shuō", v: "Nói", r: "" },
                { h: "讲", p: "jiǎng", v: "Giảng, kể", r: "" },
                { h: "看", p: "kàn", v: "Thăm, khám, nhìn, xem", r: "" },
                { h: "听", p: "tīng", v: "Nghe", r: "" },
                { h: "吃", p: "chī", v: "Ăn", r: "" },
                { h: "喝", p: "hē", v: "Uống", r: "" },
                { h: "买", p: "mǎi", v: "Mua", r: "" },
                { h: "卖", p: "mài", v: "Bán", r: "" },
                { h: "读", p: "dú", v: "Đọc", r: "" },
                { h: "穿", p: "chuān", v: "Mặc", r: "" },
                { h: "给", p: "gěi", v: "Cho", r: "" },
                { h: "请", p: "qǐng", v: "Mời", r: "" },
                { h: "问", p: "wèn", v: "Hỏi", r: "" },
                { h: "去", p: "qù", v: "Đi", r: "" },
                { h: "走", p: "zǒu", v: "Đi", r: "" },
                { h: "唱", p: "chàng", v: "Hát", r: "" },
                { h: "唱歌", p: "chànggē", v: "Ca hát", r: "" },
                { h: "睡", p: "shuì", v: "Ngủ", r: "" },
                { h: "睡觉", p: "shuìjiào", v: "Đi ngủ", r: "" },
                { h: "立", p: "lì", v: "Đứng", r: "" },
                { h: "坐", p: "zuò", v: "Ngồi", r: "" },
                { h: "作", p: "zuò", v: "Làm", r: "" },
                { h: "做", p: "zuò", v: "Làm bố, mẹ, bài tập, nghề", r: "" },
                { h: "干", p: "gàn", v: "Làm", r: "" },
                { h: "弄", p: "nòng", v: "Làm bẩn, sai, vỡ", r: "" },
                { h: "当", p: "dāng", v: "Làm", r: "" },
                { h: "办", p: "bàn", v: "Làm thủ tục", r: "" },
                { h: "搞", p: "gǎo", v: "Làm", r: "" },
                { h: "借", p: "jiè", v: "Vay, mượn", r: "" },
                { h: "还", p: "huán", v: "Trả", r: "" },
                { h: "换", p: "huàn", v: "Đổi, thay", r: "" },
                { h: "笑", p: "xiào", v: "Cười", r: "" },
                { h: "哭", p: "kū", v: "Khóc", r: "" },
                { h: "懂", p: "dǒng", v: "Hiểu", r: "" },
                { h: "明白", p: "míngbái", v: "Biết", r: "" },
                { h: "等", p: "děng", v: "Chờ đợi", r: "" },
                { h: "进", p: "jìn", v: "Vào", r: "" },
                { h: "洗澡", p: "xǐzǎo", v: "Tắm", r: "" },
                { h: "玩", p: "wán", v: "Chơi", r: "" },
                { h: "结婚", p: "jiéhūn", v: "kết hôn", r: "" },
                { h: "爱", p: "ài", v: "Yêu", r: "" },
                { h: "喜欢", p: "xǐhuan", v: "Thích", r: "" },
                { h: "来", p: "lái", v: "đến", r: "" },
                { h: "到", p: "dào", v: "đến", r: "" },
                { h: "飞", p: "fēi", v: "Bay", r: "" },
                { h: "上", p: "shàng", v: "lên", r: "" },
                { h: "下", p: "xià", v: "Xuống", r: "" },
                { h: "拍", p: "pāi", v: "vỗ, đập", r: "" },
                { h: "要", p: "yào", v: "Cần, muốn", r: "" },
                { h: "能", p: "néng", v: "có thể", r: "" },
                { h: "会", p: "huì", v: "Biết, sẽ", r: "" },
                { h: "知道", p: "zhīdào", v: "Biết", r: "" },
                { h: "可以", p: "kěyǐ", v: "Có thể", r: "" },
                { h: "应该", p: "yīnggāi", v: "Nên", r: "" },
                { h: "敢", p: "gǎn", v: "Dám", r: "" },
                { h: "想", p: "xiǎng", v: "muốn, nhớ", r: "" },
                { h: "骑", p: "qí", v: "Cưỡi, đi", r: "" },
                { h: "出", p: "chū", v: "Ra, xuất", r: "" },
                { h: "回", p: "huí", v: "Về", r: "" },
                { h: "在", p: "zài", v: "ở", r: "" },
                { h: "住", p: "zhù", v: "sống", r: "" },
                { h: "是", p: "shì", v: "Là, phải, vâng", r: "" },
                { h: "有", p: "yǒu", v: "Có", r: "" },
                { h: "认识", p: "rènshi", v: "quen", r: "" },
                { h: "学习", p: "xuéxí", v: "học tập", r: "" },
                { h: "上班", p: "shàngbān", v: "Đi làm", r: "" },
                { h: "下班", p: "xiàbān", v: "Tan ca", r: "" },
                { h: "加班", p: "jiābān", v: "Tăng ca", r: "" },
                { h: "请假", p: "qǐngjià", v: "Nghỉ phép", r: "" },
                { h: "上课", p: "shàngkè", v: "Đi học / Vào lớp", r: "" },
                { h: "下课", p: "xiàkè", v: "Tan học", r: "" },
                { h: "按", p: "àn", v: "ấn", r: "" },
                { h: "拉", p: "lā", v: "lôi, kéo", r: "" },
                { h: "推", p: "tuī", v: "đẩy, lùi", r: "" },
                { h: "红色", p: "hóngsè", v: "Màu đỏ", r: "" },
                { h: "黄色", p: "huángsè", v: "màu vàng", r: "" },
                { h: "紫色", p: "zǐsè", v: "Màu tím", r: "" },
                { h: "棕色", p: "zōngsè", v: "Màu nâu", r: "" },
                { h: "粉色", p: "fěnsè", v: "màu hồng", r: "" },
                { h: "游", p: "yóu", v: "bơi", r: "" },
                { h: "很", p: "hěn", v: "Rất", r: "" },
                { h: "太", p: "tài", v: "Quá", r: "" },
                { h: "不", p: "bù", v: "không", r: "" },
                { h: "没", p: "méi", v: "chưa / không", r: "" },
                { h: "吗", p: "ma", v: "không?", r: "" },
                { h: "饭", p: "fàn", v: "Cơm", r: "" },
                { h: "放", p: "fàng", v: "đặt, để", r: "" },
                { h: "饿", p: "è", v: "Đói", r: "" },
                { h: "饱", p: "bǎo", v: "No", r: "" },
                { h: "好", p: "hǎo", v: "Tốt", r: "" },
                { h: "坏", p: "huài", v: "Xấu", r: "" },
                { h: "新", p: "xīn", v: "Mới", r: "" },
                { h: "旧", p: "jiù", v: "Cũ", r: "" },
                { h: "胖", p: "pàng", v: "Béo", r: "" },
                { h: "瘦", p: "shòu", v: "Gầy", r: "" },
                { h: "长", p: "cháng", v: "Dài", r: "" },
                { h: "短", p: "duǎn", v: "Ngắn", r: "" },
                { h: "大", p: "dà", v: "To", r: "" },
                { h: "小", p: "xiǎo", v: "Nhỏ", r: "" },
                { h: "近", p: "jìn", v: "gần", r: "" },
                { h: "远", p: "yuǎn", v: "Xa", r: "" },
                { h: "东西", p: "dōngxi", v: "đồ đạc", r: "" },
                { h: "动作", p: "dòngzuò", v: "động tác", r: "" },
                { h: "动物", p: "dòngwù", v: "Động vật", r: "" },
                { h: "这", p: "zhè", v: "Đây, Này", r: "" },
                { h: "那", p: "nà", v: "Kia, đó", r: "" },
                { h: "每", p: "měi", v: "Mỗi", r: "" },
                { h: "次", p: "cì", v: "lần", r: "" },
                { h: "对", p: "duì", v: "đúng / đối với", r: "" },
                { h: "错", p: "cuò", v: "sai", r: "" },
                { h: "高兴", p: "gāoxìng", v: "Vui", r: "" },
                { h: "难过", p: "nánguò", v: "Buồn", r: "" },
                { h: "快", p: "kuài", v: "nhanh", r: "" },
                { h: "慢", p: "màn", v: "chậm", r: "" },
                { h: "漂亮", p: "piàoliang", v: "xinh đẹp", r: "" },
                { h: "帅哥", p: "shuàigē", v: "Đẹp trai", r: "" },
                { h: "丑", p: "chǒu", v: "Xấu", r: "" },
                { h: "本", p: "běn", v: "quyển", r: "" },
                { h: "个", p: "gè", v: "Cái", r: "" },
                { h: "张", p: "zhāng", v: "tờ, tấm (chiếc)", r: "" },
                { h: "条", p: "tiáo", v: "con, chiếc", r: "" },
                { h: "只", p: "zhī", v: "Con", r: "" },
                { h: "忙", p: "máng", v: "Bận", r: "" },
                { h: "累", p: "lèi", v: "Mệt", r: "" },
                { h: "数字", p: "shùzì", v: "số, số đếm", r: "" },
                { h: "零", p: "líng", v: "0", r: "" },
                { h: "一", p: "yī", v: "1", r: "" },
                { h: "二", p: "èr", v: "2", r: "" },
                { h: "三", p: "sān", v: "3", r: "" },
                { h: "四", p: "sì", v: "4", r: "" },
                { h: "五", p: "wǔ", v: "5", r: "" },
                { h: "六", p: "liù", v: "6", r: "" },
                { h: "七", p: "qī", v: "7", r: "" },
                { h: "八", p: "bā", v: "8", r: "" },
                { h: "九", p: "jiǔ", v: "9", r: "" },
                { h: "十", p: "shí", v: "10", r: "" },
                { h: "百", p: "bǎi", v: "Trăm", r: "" },
                { h: "千", p: "qiān", v: "Nghìn", r: "" },
    { h: "说话", p: "shuō huà", v: "Nói chuyện, trao đổi", r: "" },
    { h: "讲话", p: "jiǎng huà", v: "Nói chuyện, trao đổi", r: "" },
    { h: "谈话", p: "tán huà", v: "Nói chuyện, trao đổi", r: "" },
    { h: "聊天", p: "liáo tiān", v: "Nói chuyện, trao đổi", r: "" },
    { h: "沟通", p: "gōu tōng", v: "Trao đổi", r: "" },
    { h: "交往", p: "jiāo wǎng", v: "Trò chuyện, giao tiếp", r: "" },
    { h: "喊", p: "hǎn", v: "Hét, la", r: "" },
    { h: "咬", p: "yǎo", v: "Cắn, đớp", r: "" },
    { h: "尝", p: "cháng", v: "Nếm, thử", r: "" },
    { h: "骂", p: "mà", v: "Mắng, chửi", r: "" },
    { h: "拿", p: "ná", v: "Cầm, nắm", r: "" },
    { h: "打", p: "dǎ", v: "Đánh, chơi, gọi", r: "" },
    { h: "写", p: "xiě", v: "Viết", r: "" },
    { h: "擦", p: "cā", v: "Lau, chùi", r: "" },
    { h: "洗", p: "xǐ", v: "Giặt, rửa, vo", r: "" },
    { h: "摘", p: "zhāi", v: "Vặt, hái", r: "" },
    { h: "偷", p: "tōu", v: "Trộm", r: "" },
    { h: "抓", p: "zhuā", v: "Vỗ, tóm", r: "" },
    { h: "搬", p: "bān", v: "Chuyển, dời", r: "" },
    { h: "拧", p: "nǐng", v: "Vặn", r: "" },
    { h: "站", p: "zhàn", v: "Đứng, bến, trạm", r: "" },
    { h: "踢", p: "tī", v: "Sút, đá", r: "" },
    { h: "跑", p: "pǎo", v: "Chạy", r: "" },
    { h: "跑步", p: "pǎo bù", v: "Chạy bộ", r: "" },
    { h: "跳", p: "tiào", v: "Nhảy", r: "" },
    { h: "跳舞", p: "tiào wǔ", v: "Khiêu vũ", r: "" },
    { h: "爬", p: "pá", v: "Leo, trèo", r: "" },
    { h: "踩", p: "cǎi", v: "Dẫm, đạp", r: "" },
    { h: "起", p: "qǐ", v: "Dậy", r: "" },
    { h: "起床", p: "qǐ chuáng", v: "Thức dậy", r: "" },
    { h: "开", p: "kāi", v: "Mở", r: "" },
    { h: "关", p: "guān", v: "Đóng", r: "" },
    { h: "念", p: "niàn", v: "Đọc, niệm", r: "" },
    { h: "教", p: "jiāo", v: "Dạy, đọc", r: "" },
    { h: "叫", p: "jiào", v: "Gọi, kêu, gáy", r: "" },
    { h: "交", p: "jiāo", v: "Giao, nộp, kết (bạn)", r: "" },
    { h: "脱", p: "tuō", v: "Cởi", r: "" },
    { h: "了解", p: "liǎo jiě", v: "Hiểu, tìm hiểu", r: "" },
    { h: "切", p: "qiē", v: "Thái, bổ", r: "" },
    { h: "挖", p: "wā", v: "Đào", r: "" },
    { h: "卷", p: "juǎn", v: "Cuộn, cuốn", r: "" },
    { h: "抱", p: "bào", v: "Ôm", r: "" },
    { h: "翻", p: "fān", v: "Dịch", r: "" },
    { h: "撕", p: "sī", v: "Xé", r: "" },
    { h: "搓", p: "cuō", v: "Vò, chà", r: "" },
    { h: "种", p: "zhòng", v: "Trồng", r: "" },
    { h: "画", p: "huà", v: "Vẽ", r: "" },
    { h: "离婚", p: "lí hūn", v: "Ly hôn", r: "" },
    { h: "吵架", p: "chǎo jià", v: "Cãi nhau", r: "" },
    { h: "打架", p: "dǎ jià", v: "Đánh nhau", r: "" },
    { h: "讨论", p: "tǎo lùn", v: "Thảo luận", r: "" },
    { h: "批评", p: "pī píng", v: "Phê bình", r: "" },
    { h: "表扬", p: "biǎo yáng", v: "Biểu dương", r: "" },
    { h: "吹", p: "chuī", v: "Thổi", r: "" },
    { h: "过", p: "guò", v: "Qua, đi qua", r: "" },
    { h: "休息", p: "xiū xi", v: "Nghỉ ngơi", r: "" },
    { h: "拖地", p: "tuō dì", v: "Lau nhà", r: "" },
    { h: "刷", p: "shuā", v: "Đánh răng", r: "" },
    { h: "烧水", p: "shāo shuǐ", v: "Đun nước", r: "" },
    { h: "熨", p: "yùn", v: "Là, ủi", r: "" },
    { h: "晾", p: "liàng", v: "Phơi", r: "" },
    { h: "扫地", p: "sǎo dì", v: "Quét nhà", r: "" },
    { h: "洗碗", p: "xǐ wǎn", v: "Rửa bát", r: "" },
    { h: "洗手", p: "xǐ shǒu", v: "Rửa tay", r: "" },
    { h: "挂", p: "guà", v: "Treo, móc", r: "" },
    { h: "签名", p: "qiān míng", v: "Ký tên", r: "" },
    { h: "拍照", p: "pāi zhào", v: "Chụp ảnh", r: "" },
    { h: "照相", p: "zhào xiàng", v: "Chụp ảnh", r: "" },
    { h: "开会", p: "kāi huì", v: "Họp", r: "" },
    { h: "骑车", p: "qí chē", v: "Lái xe,đi xe(đạp/máy)", r: "" },
    { h: "开车", p: "kāi chē", v: "Lái xe (ô tô)", r: "" },
    { h: "做饭", p: "zuò fàn", v: "Nấu cơm", r: "" },
    { h: "送", p: "sòng", v: "Tiễn, tặng", r: "" },
    { h: "寄", p: "jì", v: "Gửi", r: "" },
    { h: "收", p: "shōu", v: "Nhận", r: "" },
    { h: "存", p: "cún", v: "Gửi", r: "" },
    { h: "多", p: "duō", v: "Nhiều", r: "" },
    { h: "少", p: "shǎo", v: "Ít", r: "" },
    { h: "便宜", p: "piányi", v: "Rẻ", r: "" },
    { h: "贵", p: "guì", v: "Đắt", r: "" },
    { h: "美丽", p: "měilì", v: "Đẹp", r: "" },
    { h: "香", p: "xiāng", v: "Thơm", r: "" },
    { h: "臭", p: "chòu", v: "Thối", r: "" },
    { h: "甜", p: "tián", v: "Ngọt", r: "" },
    { h: "酸", p: "suān", v: "Chua", r: "" },
    { h: "苦", p: "kǔ", v: "Đắng", r: "" },
    { h: "辣", p: "là", v: "Cay", r: "" },
    { h: "咸", p: "xián", v: "Mặn", r: "" },
    { h: "淡", p: "dàn", v: "Nhạt", r: "" },
    { h: "厚", p: "hòu", v: "Dày", r: "" },
    { h: "薄", p: "báo", v: "Mỏng", r: "" },
    { h: "聪明", p: "cōngmíng", v: "Thông minh", r: "" },
    { h: "笨", p: "bèn", v: "Đần, ngốc", r: "" },
    { h: "可爱", p: "kě'ài", v: "Đáng yêu", r: "" },
    { h: "热情", p: "rèqíng", v: "Nhiệt tình", r: "" },
    { h: "认真", p: "rènzhēn", v: "Chăm chỉ, nghiêm túc", r: "" },
    { h: "严格", p: "yángé", v: "Nghiêm khắc", r: "" },
    { h: "白", p: "bái", v: "Trắng", r: "" },
    { h: "黑", p: "hēi", v: "Đen", r: "" },
    { h: "蓝", p: "lán", v: "Xanh lam", r: "" },
    { h: "绿", p: "lǜ", v: "Xanh lá", r: "" },
    { h: "红", p: "hóng", v: "Đỏ", r: "" },
    { h: "粉", p: "fěn", v: "Hồng", r: "" },
    { h: "干净", p: "gānjìng", v: "Sạch", r: "" },
    { h: "脏", p: "zāng", v: "Bẩn", r: "" },
    { h: "硬", p: "yìng", v: "Cứng", r: "" },
    { h: "软", p: "ruǎn", v: "Mềm", r: "" },
    { h: "开心", p: "kāixīn", v: "Vui", r: "" },
    { h: "快乐", p: "kuàilè", v: "Vui", r: "" },
    { h: "愉快", p: "yúkuài", v: "Vui", r: "" },
    { h: "难", p: "nán", v: "Khó", r: "" },
    { h: "容易", p: "róngyì", v: "Dễ", r: "" },
    { h: "热", p: "rè", v: "Nóng", r: "" },
    { h: "冷", p: "lěng", v: "Lạnh", r: "" },
    { h: "暖和", p: "nuǎnhuo", v: "Ấm áp", r: "" },
    { h: "凉快", p: "liángkuai", v: "Mát mẻ", r: "" },
    { h: "难受", p: "nánshòu", v: "Khó chịu", r: "" },
    { h: "舒服", p: "shūfu", v: "Thoải mái", r: "" },
    { h: "重", p: "zhòng", v: "Nặng", r: "" },
    { h: "轻", p: "qīng", v: "Nhẹ", r: "" },
    { h: "老", p: "lǎo", v: "Già", r: "" },
    { h: "年轻", p: "niánqīng", v: "Trẻ", r: "" },
    { h: "高", p: "gāo", v: "Cao", r: "" },
    { h: "矮", p: "ǎi", v: "Lùn", r: "" },
    { h: "低", p: "dī", v: "Thấp", r: "" },

            ];
if (typeof window !== 'undefined') {
    window.masterData = masterData;
}
